gazebo: {auto_disable_bodies: false, cfm: 0.0, contact_max_correcting_vel: 100.0,
  contact_surface_layer: 0.001, erp: 0.2, gravity_x: 0.0, gravity_y: 0.0, gravity_z: -9.8,
  max_contacts: 20, max_update_rate: 1000.0, sor_pgs_iters: 50, sor_pgs_precon_iters: 0,
  sor_pgs_rms_error_tol: 0.0, sor_pgs_w: 1.3, time_step: 0.001}
gazebo_gui: {auto_disable_bodies: false, cfm: 0.0, contact_max_correcting_vel: 100.0,
  contact_surface_layer: 0.001, erp: 0.2, gravity_x: 0.0, gravity_y: 0.0, gravity_z: -9.8,
  max_contacts: 20, max_update_rate: 1000.0, sor_pgs_iters: 50, sor_pgs_precon_iters: 0,
  sor_pgs_rms_error_tol: 0.0, sor_pgs_w: 1.3, time_step: 0.001}
node2: {ball_vel: 3.0, x0: 5.0, y0: 1.0, z0: 0.0}
robot_description: "<robot name=\"planet_model\">\n\n  <!-- root link, on the ground\
  \ just below the model origin -->\n  <link name=\"/base_footprint\">\n   <inertial>\n\
  \      <mass value=\"50\" />\n      <origin xyz=\"0 0 0\" />\n      <inertia ixx=\"\
  50.0\" ixy=\"0.0\" ixz=\"0.0\"\n        iyy=\"50.0\" iyz=\"0.0\"\n        izz=\"\
  50.0\" />\n    </inertial>\n    <visual>\n      <geometry>\n              <sphere\
  \ radius = \"0.2\"/>\n          </geometry>\n          <material name = \"white\"\
  >\n              <color rgba = \"1 1 1 1\"/>\n          </material>\n    </visual>\n\
  \    <collision>\n      <origin xyz=\"0 0 0\" />\n      <geometry>\n        <sphere\
  \ radius = \"0.2\"/>\n      </geometry>\n    </collision>\n  </link>\n\n\n  <gazebo>\n\
  \    <plugin name=\"object_controller\" filename=\"libgazebo_ros_planar_move.so\"\
  >\n      <commandTopic>/cmd_vel</commandTopic>\n      <odometryTopic>/odom</odometryTopic>\n\
  \      <odometryFrame>/map</odometryFrame>\n      <odometryRate>20.0</odometryRate>\n\
  \      <robotBaseFrame>/base_footprint</robotBaseFrame>\n    </plugin>\n  </gazebo>\n\
  \n</robot>\n"
rosdistro: 'kinetic

  '
roslaunch:
  uris: {host_mengbys__34335: 'http://mengbys:34335/'}
rosversion: '1.12.14

  '
run_id: df6ddb4e-f219-11e9-811a-1002b530e3f0
use_sim_time: true
